config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "home#index"
	resources :users
  	get 'password_resets/new'
  	resources :password_resets
	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	get '/logout' => 'sessions#destroy'
	get "/auth/google_oauth2/callback" => "users#google_oauth2"
	resources "foods"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
	belongs_to :user, required: false
 	scope :item, -> (input_item) { where("item ILIKE ?", "%#{input_item}%") }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :foods 
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  before_create {generate_token(:auth_token)}


  def user?
      self.type == "User"
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  	def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
        user = User.create(
           email: data['email'],
           password: SecureRandom.hex
        )
    end
    user
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    # @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

	def index
		@food = Food.all
		@search = Food.where(nil)
		filtering_params(params).each do |key, value|
			@search = @search.public_send(key, value) if value.present?	
		end

		respond_to do |format| 
			format.html
			format.js 
		end 
	end

	def create
		@food = current_user.foods.new(food_params)
		if @food.save
			redirect_to root_path
		else
			redirect_to new_food_path
		end

	end

	def new
		@food = Food.new
	end


	def show
	end

	def edit
		@food = current_user.foods.find(params[:id])
	end
	
	def update
		@food = Food.find(params[:id])
		@food.update_attributes(food_params)
		redirect_to root_path
	end

    def destroy
    	@food = Food.delete(params[:id])
    	@number = params[:id]
    	redirect_to root_path
    end

	private
	 def find_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:item, :price, :location, :description, {image:[]})
    end

    def filtering_params(params)
    	params.slice(:item , :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  	def new
	end

	  def create
	  	user = User.find_by_email(params[:email])
	  	user.send_password_reset if user
	  	redirect_to root_path, :notice => "Check Your Email For Reset Password"
	  end

	  def edit
	  	@user = User.find_by_password_reset_token!(params[:password_reset_token])
	  end

	  def update
	  	@user = User.find_by_password_reset_token!(params[:password_reset_token])
	  	if @user.password_reset_sent_at <=> 2.hours.ago
	  		redirect_to new_password_reset_path , :alert =>"Password reset has expired."
	  	elsif @user.update_attributes(user_params)
	  		redirect_to root_path, :notice => "Password has been reset!"
	  	else
	  		redirect_to edit_password_reset_path
	  end
	end

	def show
	end
end

private
	def user_params
    	params.require(:user).permit(:password_digest,:password, :password_confirmation)
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.where(email: params[:email]).first
	  	if user && user.authenticate(params[:password])
		    session[:user_id] = user.id # important to only store userid in cookie(session) and not other information of the user to not have too big a cookie and risk "cookie overflow".
		    flash[:notice] = "Welcome, you've logged in."
		    redirect_to root_path
	  else
	    	flash[:error] = "There is something wrong with your username or password."
	    	redirect_to login_path
	  end
	end
	
	def edit
	end

	def destroy
	  session[:user_id] = nil
	  flash[:notice] = "You've logged out."
	  redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save 
			session[:user_id] = @user.id
    		flash[:notice] = "You are registered."
			redirect_to root_url
		else
			flash[:notice] = "Invalid email or password"
			redirect_to new_user_path
		end
	end

	def google_oauth2
	    @user = User.from_omniauth(request.env['omniauth.auth'])          
	    session[:user_id] = @user.id                                       
	    redirect_to root_path                                        
	end

	private
	def user_params
	  params.require(:user).permit(:email,:password_confirmation ,:password,:password_digest, :_destroy)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_partial.html.erb
<% @search.each do |p| %>
<h1><%= p.item %></h1>
<iframe class ="map"
	 height="250px"
	 frameborder="0" style="border:0"
	 src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBX8hQcoSEtucwisPltvD2u0Xsl7nZg77I
	   &q=<%= (p.location).gsub(/(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)/, '\1+\2+\3+\4+\5+\6+\7+\8')%>&q=seattle+washington&q=arizona" allowfullscreen>
	</iframe>
<%= p.price %>
<% end %>

app/views/foods/edit.html.erb
Edit your restaurant
<%= form_for @food do |f| %>

<div class="food_field">
<%= f.label :item %>
<%= f.text_field :item %>
</div>

<div class="food_field">
<%= f.label :location %>
<%= f.text_field :location %>
</div>

<div class="furniture_field">
<%= f.label :price %>
<%= f.text_field :price %></div>

<% end %>

app/views/foods/index.html.erb
<h1>Restaurant</h1>
	<div id="search">
		<%= form_tag foods_path,method: :get , remote: true do %>
			<%= text_field_tag :item,params[:item] %>
			<%= submit_tag 'Search', :class => "w3-bar-item w3-button" %>
		<%end%>
	</div>
	<div id="searchitem">
	</div>
	<div id="alllist">
	<% @food.each do |f| %>
	<h2><%= f.item %></h2>
	<h3><%= f.location %></h3>
	 <iframe class ="map"
	 height="250px"
	 frameborder="0" style="border:0"
	 src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBX8hQcoSEtucwisPltvD2u0Xsl7nZg77I
	   &q=<%= (f.location).gsub(/(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)/, '\1+\2+\3+\4+\5+\6+\7+\8')%>&q=seattle+washington&q=arizona" allowfullscreen>
	</iframe>
	<%=f.price %>
	<%if current_user == f.user%>
	<p> <%=link_to "edit", edit_food_path(f)%></p>
	<% end %>
	<% end %>
	</div>
	<%= link_to 'Create Your Listing', new_food_path %>

app/views/foods/index.js.erb
$("#alllist").html("");
$("#searchitem").html("");
$('#searchitem').append('<%= escape_javascript (render(partial: 'partial')) %>');

app/views/foods/new.html.erb
<%= form_for @food do |f| %>

<div class="food_field">
<%= f.label :item %>
<%= f.text_field :item %>
</div>

<div class="food_field">
<%= f.label :location %>
<%= f.text_field :location %>
</div>

<div class="furniture_field">
<%= f.label :price %>
<%= f.text_field :price %></div>

<div class="furniture_field">
<%= f.file_field :image %>
<%= f.submit 'Upload' %>
</div>

<% end %>

app/views/home/index.html.erb
<form class="form-inline my-2 my-lg-0" style="float: right;">
      <% if current_user %>
        Signed in as <%= current_user.email %> | <%= link_to "Logout", '/logout' %>

      <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', new_user_path %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
      <% end %>
    </form>

<span> <span class="w3-hide-small">Kos</span> Tlitch</span>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div >
  <div id="myNavbar">
    <a href="/">HOME</a>
    <a href="/login"><i class="fa fa-user"></i> LOGIN</a>
    <a href="/foods"><i class="fa fa-th"></i> RESTAURANT</a>
    <a href="/users/new"><i class="fa fa-briefcase"></i> REGISTER</a>
      <i class="fa fa-search"></i>
    </a>
  </div>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
Password Reset
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
<% if @user.errors.any? %>
	<div class="errorMessage">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user .errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<%= f.submit "Reset Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset your password</h1>
<%= form_tag password_resets_url do %>
	<%= label_tag :email %>
	<%= text_field_tag :email,params[:email] %>
	<%= submit_tag "Reset Password" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |n| %>

<div id="sign_field">
	<%= n.label :email %>
	<%= n.text_field :email %>
</div>

<div id="sign_field">
	<%= n.label :password %>
	<%= n.password_field :password %>
</div>

<div id="sign_field">
	<%= n.label :password_confirmation %>
	<%= n.password_field :password_confirmation %>
</div>
<%= n.submit "sign up"%>

<% end %>